import { AlertTriangle, ArrowLeft, ArrowRightLeft, Bot, CalendarCheck, Mic, MicOff, Moon, User, UserSquare2 } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Timeline } from "@/components/app/timeline";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DemoTag, KeyValue, PageHeader } from "@/components/ui/misc";
import { requireAuth } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { customerName, formatDateTime, formatDuration, formatPhone } from "@/lib/format";
import { CALL_OUTCOME, CALL_STATUS, LEAD_STATUS, URGENCY } from "@/lib/labels";
import type { CallSummary } from "@/lib/providers/types";
import { cn } from "@/lib/utils";

export default async function CallDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const auth = await requireAuth("calls:view");
  const { id } = await params;
  const call = await db.call.findFirst({
    where: { id, organizationId: auth.orgId },
    include: {
      transcripts: { orderBy: { seq: "asc" } },
      customer: true,
      lead: true,
      appointment: { include: { technician: true } },
    },
  });
  if (!call) notFound();
  const org = await db.organization.findUniqueOrThrow({ where: { id: auth.orgId }, select: { timezone: true } });
  const events = await db.leadEvent.findMany({
    where: { organizationId: auth.orgId, OR: [{ metadata: { path: ["callId"], equals: call.id } }, ...(call.leadId ? [{ leadId: call.leadId, createdAt: { gte: call.startedAt } }] : [])] },
    orderBy: { createdAt: "asc" },
    take: 40,
  });
  const summary = call.summary as CallSummary | null;
  const tz = org.timezone;

  return (
    <>
      <Link href="/calls" className="mb-3 inline-flex items-center gap-1 text-sm text-muted hover:text-ink">
        <ArrowLeft className="size-4" /> All calls
      </Link>
      <PageHeader
        title={call.callerName ?? formatPhone(call.fromNumber)}
        description={`${formatPhone(call.fromNumber)} · ${formatDateTime(call.startedAt, tz)} · ${formatDuration(call.durationSeconds)}`}
        actions={
          <div className="flex flex-wrap gap-1.5">
            <Badge tone={CALL_STATUS[call.status].tone}>{CALL_STATUS[call.status].label}</Badge>
            {call.outcome ? <Badge tone={CALL_OUTCOME[call.outcome].tone}>{CALL_OUTCOME[call.outcome].label}</Badge> : null}
            {call.isEmergency ? (
              <Badge tone="red">
                <AlertTriangle /> Emergency
              </Badge>
            ) : null}
            {call.isAfterHours ? (
              <Badge tone="violet">
                <Moon /> After hours
              </Badge>
            ) : null}
            {call.isSimulated ? <DemoTag>Simulated call</DemoTag> : null}
          </div>
        }
      />
      <div className="grid gap-4 lg:grid-cols-3">
        <div className="space-y-4 lg:col-span-2">
          {summary ? (
            <Card>
              <CardHeader>
                <CardTitle>AI summary</CardTitle>
                <span className="text-[11px] text-muted">Generated by {summary.generatedBy === "openai" ? "OpenAI" : "rules engine"}</span>
              </CardHeader>
              <CardContent className="space-y-3">
                <p className="text-base font-medium text-ink">{summary.headline}</p>
                <dl className="grid gap-x-6 sm:grid-cols-2">
                  <KeyValue label="Intent">{summary.intent}</KeyValue>
                  <KeyValue label="Service">{summary.serviceRequested ?? "—"}</KeyValue>
                  <KeyValue label="Urgency">{summary.urgency.toLowerCase()}</KeyValue>
                  <KeyValue label="Outcome">{summary.outcome}</KeyValue>
                </dl>
                {summary.keyDetails.length ? (
                  <div>
                    <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-muted">Key details</p>
                    <ul className="list-disc space-y-0.5 pl-5 text-sm text-ink-2">
                      {summary.keyDetails.map((d) => (
                        <li key={d}>{d}</li>
                      ))}
                    </ul>
                  </div>
                ) : null}
                {summary.nextSteps.length ? (
                  <div>
                    <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-muted">Next steps</p>
                    <ul className="list-disc space-y-0.5 pl-5 text-sm text-ink-2">
                      {summary.nextSteps.map((d) => (
                        <li key={d}>{d}</li>
                      ))}
                    </ul>
                  </div>
                ) : null}
              </CardContent>
            </Card>
          ) : null}
          <Card>
            <CardHeader>
              <CardTitle>Transcript</CardTitle>
              <span className="flex items-center gap-1 text-xs text-muted">
                {call.recordingStatus === "RECORDED" ? <Mic className="size-3.5" /> : <MicOff className="size-3.5" />}
                {call.recordingStatus === "RECORDED" ? "Recording on file (audio not included in demo data)" : call.isSimulated ? "Simulated — no audio recorded" : "Not recorded"}
              </span>
            </CardHeader>
            <CardContent>
              {call.transcripts.length ? (
                <ol className="space-y-3">
                  {call.transcripts.map((t) => {
                    const caller = t.speaker === "CALLER";
                    return (
                      <li key={t.id} className={cn("flex gap-2", caller ? "flex-row-reverse" : "")}>
                        <span className={cn("mt-1 flex size-7 shrink-0 items-center justify-center rounded-full", caller ? "bg-slate-200 text-ink-2" : "bg-teal-100 text-accent")} aria-hidden>
                          {caller ? <User className="size-3.5" /> : <Bot className="size-3.5" />}
                        </span>
                        <div className={cn("max-w-[80%] rounded-2xl px-3.5 py-2 text-sm", caller ? "rounded-tr-sm bg-brand text-white" : "rounded-tl-sm bg-slate-100 text-ink")}>
                          <span className="sr-only">{caller ? "Caller" : "AI"}: </span>
                          {t.text}
                        </div>
                      </li>
                    );
                  })}
                </ol>
              ) : (
                <p className="py-6 text-center text-sm text-muted">{call.status === "MISSED" || call.status === "VOICEMAIL" ? "No conversation — this call was not answered." : "No transcript available."}</p>
              )}
            </CardContent>
          </Card>
        </div>
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Caller</CardTitle>
            </CardHeader>
            <CardContent>
              <dl>
                <KeyValue label="Name">{call.customer ? <Link className="text-brand hover:underline" href={`/customers/${call.customer.id}`}>{customerName(call.customer)}</Link> : "Unknown"}</KeyValue>
                <KeyValue label="Phone">{formatPhone(call.fromNumber)}</KeyValue>
                <KeyValue label="Address">{call.customer?.address ? `${call.customer.address}, ${call.customer.city ?? ""}` : "—"}</KeyValue>
                <KeyValue label="Answered by">{call.answeredBy === "AI" ? "AI receptionist" : call.answeredBy === "STAFF" ? "Staff" : "Nobody"}</KeyValue>
                {call.transferredTo ? (
                  <KeyValue label="Handoff">
                    <span className="inline-flex items-center gap-1">
                      <ArrowRightLeft className="size-3.5" /> {call.transferredTo}
                    </span>
                  </KeyValue>
                ) : null}
                {call.textBackSentAt ? <KeyValue label="Text-back">{formatDateTime(call.textBackSentAt, tz)}</KeyValue> : null}
              </dl>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Linked records</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {call.lead ? (
                <Link href={`/leads/${call.lead.id}`} className="flex items-center gap-3 rounded-lg border border-line p-3 hover:bg-slate-50">
                  <UserSquare2 className="size-4 text-muted" />
                  <div className="flex-1">
                    <p className="text-sm font-medium text-ink">{call.lead.requestedService}</p>
                    <div className="mt-1 flex gap-1">
                      <Badge tone={LEAD_STATUS[call.lead.status].tone}>{LEAD_STATUS[call.lead.status].label}</Badge>
                      <Badge tone={URGENCY[call.lead.urgency].tone}>{URGENCY[call.lead.urgency].label}</Badge>
                    </div>
                  </div>
                </Link>
              ) : (
                <p className="text-sm text-muted">No lead linked.</p>
              )}
              {call.appointment ? (
                <Link href={`/calendar?date=${call.appointment.startAt.toISOString().slice(0, 10)}&appt=${call.appointment.id}`} className="flex items-center gap-3 rounded-lg border border-line p-3 hover:bg-slate-50">
                  <CalendarCheck className="size-4 text-muted" />
                  <div>
                    <p className="text-sm font-medium text-ink">{call.appointment.title}</p>
                    <p className="text-xs text-muted">
                      {formatDateTime(call.appointment.startAt, tz)} · {call.appointment.technician?.name ?? "Unassigned"}
                    </p>
                  </div>
                </Link>
              ) : null}
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Event timeline</CardTitle>
            </CardHeader>
            <CardContent>
              <Timeline events={events} tz={tz} />
            </CardContent>
          </Card>
          <Button asChild variant="outline" className="w-full">
            <Link href="/calls/simulator">Run another simulation</Link>
          </Button>
        </div>
      </div>
    </>
  );
}
